window.ACCOMMODATION_DATA = {
  "Hideaway Cottage": {
    id: "hideaway_cottage",
    title: "Hideaway Cottage",
    displayTitle: "Hideaway Cottage",
    shortSummary:
      "A cosy on-site cottage with plenty of room for a relaxed night-before stay.",
    timingLabel: "Sunday 2nd - Tuesday 4th August",
    checkoutLabel: "10am, Tuesday 4 August",
    sleepsLabel: "Sleeps 10",
    locationNote: "On the Birtsmorton Court estate and close to the wedding setting.",
    optionalNotes:
      "Includes an optional hot tub, an upstairs family bathroom, and a downstairs WC.",
    images: [
      "images/Hideaway Cottage/Hideaway Garden.webp",
      "images/Hideaway Cottage/0062.JPG",
      "images/Hideaway Cottage/b7f67847-181a-49de-9698-d0990b6d1c4d.jpg",
      "images/Hideaway Cottage/21ffe653-b32d-45cf-b49d-32547f476f9f.webp",
      "images/Hideaway Cottage/3532d07d-90b0-433b-8bc4-177e083c7ec5.webp",
      "images/Hideaway Cottage/4981f40a-0bc3-4137-82a3-9837c88e5414.webp",
      "images/Hideaway Cottage/505bdbc6-e63a-4284-baff-799808428752.webp",
      "images/Hideaway Cottage/50682839-6225-4ddd-b364-8f9477e02457.webp",
      "images/Hideaway Cottage/754e1a66-73fc-46e6-b051-0083bd1f68fb.webp",
      "images/Hideaway Cottage/7e666606-abe2-49a1-b03b-9ac612b73780.webp",
      "images/Hideaway Cottage/80a0ae23-2f19-4845-8ba5-25bb72dc683f.webp",
      "images/Hideaway Cottage/84a8b2ae-bf6b-4dc1-a6ef-7309f6d8bcc0.webp",
      "images/Hideaway Cottage/87865cd7-a775-419a-8478-aa97bf122bb1.webp",
      "images/Hideaway Cottage/88ebc0b2-15f5-49ba-8987-36cbd504fc78.webp",
      "images/Hideaway Cottage/93f15943-5397-4126-a541-255d34b577a4.webp",
      "images/Hideaway Cottage/a8d0961f-4c27-4b55-8cea-35b4aea1ae36.webp",
      "images/Hideaway Cottage/cb0b479c-77fb-4b1d-9e84-ade7a2eb580e.webp",
      "images/Hideaway Cottage/d10a411c-9c4b-4c93-bb27-29fb2a214ee0.webp",
      "images/Hideaway Cottage/df40f5cf-15ff-4a59-835f-7968cab6d8d6.webp",
      "images/Hideaway Cottage/f737ae41-b04e-4a1f-8f85-4c725b55f6d4.webp",
      "images/Hideaway Cottage/f7470c2b-9dc5-4ff1-9cea-85378a185dbf.webp",
      "images/Hideaway Cottage/Accommodation Breakdown (1).jpg",
      "images/Hideaway Cottage/Hideaway Cottage Floorplan.jpg",
    ],
  },
  "Malvern Chase Shepherd’s Hut": {
    id: "malvern_chase_hut",
    title: "Malvern Chase Shepherd’s Hut",
    displayTitle: "Your Shepherd’s Hut",
    secondaryLabel: "Malvern Chase Shepherd’s Hut",
    shortSummary:
      "A peaceful shepherd’s hut with a cosy king-sized bed and space for children on the sofa bed.",
    timingLabel: "Sunday 2nd - Tuesday 4th August",
    checkoutLabel: "10am, Tuesday 4 August",
    sleepsLabel: "Sleeps 2–4",
    locationNote: "On-site at Birtsmorton Court in a quiet countryside spot.",
    optionalNotes: "Includes a shower room and an optional hot tub.",
    images: [
      "images/Malvern Chase Shepherd's Hut/Birtsmorton Shephards Huts0048.jpg",
      "images/Malvern Chase Shepherd's Hut/14be8723-0dc8-402b-bb3e-07ab895712e0.jpg",
      "images/Malvern Chase Shepherd's Hut/1e099037-a93c-411e-9687-560fa167f699.webp",
      "images/Malvern Chase Shepherd's Hut/1f7bf4ec-b5d3-4d98-97b8-64dae50545cb.jpg",
      "images/Malvern Chase Shepherd's Hut/237ef283-2383-4ffe-969e-6a6a4def1228.jpg",
      "images/Malvern Chase Shepherd's Hut/46df647c-dc64-402d-ac19-711121e75af7.jpg",
      "images/Malvern Chase Shepherd's Hut/625bfce1-d1f7-44c8-8f83-801c7656b262.jpg",
      "images/Malvern Chase Shepherd's Hut/b62fe015-fa8e-41b6-8bd7-9686bd87bcd5.jpg",
      "images/Malvern Chase Shepherd's Hut/d5405bb3-44c2-4ac5-88bd-91455131a170.jpg",
      "images/Malvern Chase Shepherd's Hut/de810b6d-d6a6-49f5-8be9-199077f22a3b.jpg",
      "images/Malvern Chase Shepherd's Hut/e155e041-5d19-4d83-a667-db46b084d92e.jpg",
      "images/Malvern Chase Shepherd's Hut/e98c5d5d-0da6-4898-9b2f-0647f002db4d.jpg",
      "images/Malvern Chase Shepherd's Hut/f38b16df-9ae0-4bba-a826-686c42afe2ed.jpg",
      "images/Malvern Chase Shepherd's Hut/fbd9c8d5-ae6d-49b0-ba21-4fed7e411080.jpg",
    ],
  },
  "Midsummer Shepherd's Hut": {
    id: "midsummer_hut",
    title: "Midsummer Shepherd's Hut",
    displayTitle: "Your Shepherd’s Hut",
    secondaryLabel: "Midsummer Shepherd's Hut",
    shortSummary:
      "A calm, compact shepherd’s hut that’s perfect for a comfortable overnight stay.",
    timingLabel: "Sunday 2nd - Tuesday 4th August",
    checkoutLabel: "10am, Tuesday 4 August",
    sleepsLabel: "Sleeps 2",
    locationNote: "On-site and close to the main wedding areas.",
    optionalNotes: "Includes a shower room and optional hot tub access.",
    images: [
      "images/Midsummer Shepherd's Hut/Birtsmorton Shephards Huts0049.jpg",
      "images/Midsummer Shepherd's Hut/Birtsmorton Shephards Huts0046.jpg",
      "images/Midsummer Shepherd's Hut/Birtsmorton Shephards Huts0001.jpg",
      "images/Midsummer Shepherd's Hut/Birtsmorton Shephards Huts0003.jpg",
      "images/Midsummer Shepherd's Hut/Birtsmorton Shephards Huts0005.jpg",
      "images/Midsummer Shepherd's Hut/Birtsmorton Shephards Huts0007.jpg",
      "images/Midsummer Shepherd's Hut/Birtsmorton Shephards Huts0008.jpg",
      "images/Midsummer Shepherd's Hut/Birtsmorton Shephards Huts0009.jpg",
      "images/Midsummer Shepherd's Hut/Birtsmorton Shephards Huts0011.jpg",
      "images/Midsummer Shepherd's Hut/Birtsmorton Shephards Huts0044.jpg",
    ],
  },
  "Sugarloaf Shepherd's Hut": {
    id: "sugarloaf_hut",
    title: "Sugarloaf Shepherd's Hut",
    displayTitle: "Your Shepherd’s Hut",
    secondaryLabel: "Sugarloaf Shepherd's Hut",
    shortSummary:
      "A warm, tucked-away shepherd’s hut with a simple, private feel for the night.",
    timingLabel: "Sunday 2nd - Tuesday 4th August",
    checkoutLabel: "10am, Tuesday 4 August",
    sleepsLabel: "Sleeps 2",
    locationNote: "On-site at Birtsmorton Court.",
    optionalNotes: "Includes a shower room.",
    images: [
      "images/Sugarloaf Shepherd's Hut/Birtsmorton Shephards Huts0048.jpg",
      "images/Sugarloaf Shepherd's Hut/Birtsmorton Shephards Huts0047.jpg",
      "images/Sugarloaf Shepherd's Hut/Birtsmorton Shephards Huts0022.jpg",
      "images/Sugarloaf Shepherd's Hut/Birtsmorton Shephards Huts0025.jpg",
      "images/Sugarloaf Shepherd's Hut/Birtsmorton Shephards Huts0026.jpg",
      "images/Sugarloaf Shepherd's Hut/Birtsmorton Shephards Huts0027.jpg",
      "images/Sugarloaf Shepherd's Hut/Birtsmorton Shephards Huts0037.jpg",
      "images/Sugarloaf Shepherd's Hut/Birtsmorton Shephards Huts0039.jpg",
      "images/Sugarloaf Shepherd's Hut/Birtsmorton Shephards Huts0040.jpg",
      "images/Sugarloaf Shepherd's Hut/Birtsmorton Shephards Huts0043.jpg",
    ],
  },
  "Berrow Lodge": {
    id: "berrow_lodge",
    title: "Berrow Lodge",
    displayTitle: "Berrow Lodge",
    shortSummary:
      "A spacious lodge with room to settle in comfortably after the celebrations.",
    timingLabel: "Sunday 2nd - Tuesday 4th August",
    checkoutLabel: "10am, Tuesday 4 August",
    sleepsLabel: "Sleeps 6",
    locationNote: "Off the estate, around 0.5 miles from the venue.",
    optionalNotes:
      "Includes three bedrooms, a family bathroom upstairs, and a downstairs WC.",
    images: [
      "images/Berrow Lodge/2. Berrow Lodge.jpg",
      "images/Berrow Lodge/3. Berrow Lodge exterior.jpg",
      "images/Berrow Lodge/Living Room.jpg",
      "images/Berrow Lodge/Kitchen.jpg",
      "images/Berrow Lodge/Dining Room.jpg",
      "images/Berrow Lodge/Bedroom 1.jpg",
      "images/Berrow Lodge/Bedroom 2.jpg",
      "images/Berrow Lodge/Bedroom 3.jpg",
      "images/Berrow Lodge/Family Bathroom.jpg",
      "images/Berrow Lodge/1. Berrow Lodge Floorplan.jpg",
    ],
  },
  "Swinyard Lodge": {
    id: "swinyard_lodge",
    title: "Swinyard Lodge",
    displayTitle: "Swinyard Lodge",
    shortSummary:
      "A roomy single-level lodge that works beautifully for a relaxed family stay.",
    timingLabel: "Sunday 2nd - Tuesday 4th August",
    checkoutLabel: "10am, Tuesday 4 August",
    sleepsLabel: "Sleeps 8",
    locationNote: "Close to the venue and easy for a comfortable overnight stay.",
    optionalNotes:
      "Single-level, with three bedrooms, a king-sized sofa bed, a family bathroom, and one ensuite.",
    images: [
      "images/Swinyard Lodge/Birtmorton Cottages0151.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0148.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0147.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0100.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0104.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0105.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0109.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0110.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0111.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0113.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0114.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0117.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0118.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0120.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0124.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0128.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0132.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0136.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0137.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0138.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0139.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0143.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0144.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0150.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0161.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0163.jpg",
      "images/Swinyard Lodge/Birtmorton Cottages0166.jpg",
      "images/Swinyard Lodge/Swinyard Lodge Floorplan.jpg",
    ],
  },
  "Georgian Wing": {
    id: "georgian_wing",
    title: "Georgian Wing",
    displayTitle: "Georgian Wing",
    shortSummary:
      "A lovely room in the Georgian Wing, perfect for staying close to the heart of the wedding weekend.",
    timingLabel: "Sunday 2nd - Tuesday 4th August",
    checkoutLabel: "10am, Tuesday 4 August",
    sleepsLabel: "Sleeps 2",
    locationNote: "Located within the main house and close to the main wedding areas.",
    optionalNotes: "Ideal for a couple wanting to be right near the celebrations.",
    images: [
      "images/Georgian Wing/GEORGE&LAURA-0318.jpg",
      "images/Georgian Wing/Michelle+Guillaume80.jpg",
      "images/Georgian Wing/B&AWedding-747.jpg",
      "images/Georgian Wing/BigDayProductions-046.jpg",
      "images/Georgian Wing/Emma  Josh -25.jpg",
      "images/Georgian Wing/GEORGE&LAURA-0005.jpg",
      "images/Georgian Wing/LN-Birtsmorton Court-Malvern-Wedding-116.jpg",
      "images/Georgian Wing/Matt Godman Wedding Photography-52.jpg",
      "images/Georgian Wing/Michelle+Guillaume73.jpg",
      "images/Georgian Wing/S&A - Birtsmorton Court Wedding - Pedge Photography Wedding Photographer Cotswolds -121.jpg",
      "images/Georgian Wing/Yasmin_Aneesh_Iris_and_Ivy_Photography-464.jpg",
      "images/Georgian Wing/walking.PNG",
    ],
  },
  "Georgian Suite": {
    id: "georgian_suite",
    title: "Georgian Suite",
    displayTitle: "Georgian Suite",
    shortSummary:
      "A lovely option for a couple staying close to the heart of the wedding weekend.",
    timingLabel: "Sunday 2nd - Tuesday 4th August",
    checkoutLabel: "10am, Tuesday 4 August",
    sleepsLabel: "Sleeps 2",
    locationNote: "Located within the main house and close to the main wedding areas.",
    optionalNotes: "Ideal for a couple wanting to be right near the celebrations.",
    images: [
      "images/Georgian Wing/GEORGE&LAURA-0318.jpg",
      "images/Georgian Wing/Michelle+Guillaume80.jpg",
      "images/Georgian Wing/B&AWedding-747.jpg",
      "images/Georgian Wing/BigDayProductions-046.jpg",
      "images/Georgian Wing/Emma  Josh -25.jpg",
      "images/Georgian Wing/GEORGE&LAURA-0005.jpg",
      "images/Georgian Wing/LN-Birtsmorton Court-Malvern-Wedding-116.jpg",
      "images/Georgian Wing/Matt Godman Wedding Photography-52.jpg",
      "images/Georgian Wing/Michelle+Guillaume73.jpg",
      "images/Georgian Wing/S&A - Birtsmorton Court Wedding - Pedge Photography Wedding Photographer Cotswolds -121.jpg",
      "images/Georgian Wing/Yasmin_Aneesh_Iris_and_Ivy_Photography-464.jpg",
      "images/Georgian Wing/walking.PNG",
    ],
  },
};
