window.GUEST_HOUSEHOLDS = [
  {
    slug: "nia-alan",
    household: "Nia & Alan",
    type: "weekend",
    stay: "Georgian Wing",
    guests: ["Nia", "Alan"],
  },
  {
    slug: "nicole",
    household: "Nicole",
    type: "weekend",
    stay: "Hideaway Cottage",
    guests: ["Nicole"],
  },
  {
    slug: "ali",
    household: "Ali",
    type: "weekend",
    stay: "Hideaway Cottage",
    guests: ["Ali"],
  },
  {
    slug: "sarah-dan",
    household: "Sarah & Dan",
    type: "weekend",
    stay: "Hideaway Cottage",
    guests: ["Sarah", "Dan"],
  },
  {
    slug: "greg-lailly",
    household: "Greg & Lailly",
    type: "weekend",
    stay: "Hideaway Cottage",
    guests: ["Greg", "Lailly"],
  },
  {
    slug: "diane",
    household: "Diane",
    type: "weekend",
    stay: "Malvern Chase Shepherds Hut",
    guests: ["Diane"],
  },
  {
    slug: "graham-andrea",
    household: "Graham & Andrea",
    type: "weekend",
    stay: "Midsummer Shepherds Hut",
    guests: ["Graham", "Andrea"],
  },
  {
    slug: "malcolm-beverley",
    household: "Beverley, Malcolm, Alex & Megan",
    type: "day",
    guests: ["Beverley", "Malcolm", "Alex", "Megan"],
  },
  {
    slug: "jeff-christine",
    household: "Jeff & Christine",
    type: "day",
    guests: ["Jeff", "Christine"],
  },
  {
    slug: "danielle-simon",
    household: "Danielle & Simon",
    type: "day",
    guests: ["Danielle", "Simon"],
  },
  {
    slug: "declan-emily",
    household: "Declan & Emily",
    type: "day",
    guests: ["Declan", "Emily"],
  },
  {
    slug: "dylan",
    household: "Dylan",
    type: "day",
    guests: ["Dylan"],
  },
  {
    slug: "eleanor-keith",
    household: "Eleanor & Keith",
    type: "day",
    guests: ["Eleanor", "Keith"],
  },
  {
    slug: "liam-hannah",
    household: "Liam & Hannah",
    type: "day",
    guests: ["Liam", "Hannah"],
  },
  {
    slug: "martin",
    household: "Martin",
    type: "day",
    guests: ["Martin"],
  },
  {
    slug: "raymond-non",
    household: "Raymond & Non",
    type: "day",
    guests: ["Raymond", "Non"],
  },
  {
    slug: "stephen-wendy",
    household: "Stephen & Wendy",
    type: "day",
    guests: ["Stephen", "Wendy"],
  },
  {
    slug: "pauline-derek",
    household: "Pauline & Derek",
    type: "day",
    guests: ["Pauline", "Derek"],
  },
  {
    slug: "kevin",
    household: "Kevin",
    type: "day",
    guests: ["Kevin"],
  },
  {
    slug: "angharad",
    household: "Angharad Price",
    type: "day",
    guests: ["Angharad Price"],
  },
  {
    slug: "crystal",
    household: "Crystal Cook",
    type: "day",
    guests: ["Crystal Cook"],
  },
  {
    slug: "richard-gail",
    household: "Richard & Gail",
    type: "day",
    guests: ["Richard", "Gail"],
  },
  {
    slug: "nick-birkin",
    household: "Nick Birkin",
    type: "day",
    guests: ["Nick Birkin"],
  },
  {
    slug: "jane-jean",
    household: "Jane & Jean",
    type: "day",
    guests: ["Jane", "Jean"],
  },
  {
    slug: "john-tracy",
    household: "John & Tracy",
    type: "day",
    guests: ["John", "Tracy"],
  },
  {
    slug: "amy-robyn",
    urlSlug: "amy-robyn",
    household: "Amy & Robyn",
    guestName: "Amy & Robyn",
    type: "day",
    guestType: "day",
    isWeekend: false,
    stay: null,
    accommodation: null,
    inviteVersion: "day",
    guests: ["Amy", "Robyn"],
  },
  {
    slug: "james-elise",
    urlSlug: "james-elise",
    household: "James & Elise",
    guestName: "James & Elise",
    type: "day",
    guestType: "day",
    isWeekend: false,
    stay: null,
    accommodation: null,
    inviteVersion: "day",
    guests: ["James", "Elise"],
  },
  {
    slug: "robbie",
    urlSlug: "robbie",
    household: "Robbie",
    guestName: "Robbie",
    type: "day",
    guestType: "day",
    isWeekend: false,
    stay: null,
    accommodation: null,
    inviteVersion: "day",
    guests: ["Robbie"],
  },
  {
    slug: "jess-marcus",
    urlSlug: "jess-marcus",
    household: "Jess & Marcus",
    guestName: "Jess & Marcus",
    type: "day",
    guestType: "day",
    isWeekend: false,
    stay: null,
    accommodation: null,
    inviteVersion: "day",
    guests: ["Jess", "Marcus"],
  },
  {
    slug: "katie-ben",
    household: "Katie & Ben",
    type: "weekend",
    stay: "Berrow Lodge",
    guests: ["Katie", "Ben"],
  },
  {
    slug: "debby-kai-ruby",
    household: "Debby, Kai & Ruby",
    type: "weekend",
    stay: "Berrow Lodge",
    guests: ["Debby", "Kai", "Ruby"],
  },
  {
    slug: "lisa-anthony-holly",
    household: "Lisa, Anthony & Holly",
    type: "weekend",
    stay: "Berrow Lodge",
    guests: ["Lisa", "Anthony", "Holly"],
  },
  {
    slug: "mark",
    household: "Mark",
    type: "weekend",
    stay: "Sugarloaf Shepherds Hut",
    guests: ["Mark"],
  },
  {
    slug: "natalie-ryan",
    household: "Natalie & Ryan",
    type: "day",
    guests: ["Natalie", "Ryan"],
  },
  {
    slug: "amber-martin",
    household: "Amber & Martin",
    type: "weekend",
    stay: "Swinyard Lodge",
    guests: ["Amber", "Martin"],
  },
  {
    slug: "sofi-george-pippa",
    household: "Sofi, George & Pippa",
    type: "weekend",
    stay: "Swinyard Lodge",
    guests: ["Sofi", "George", "Pippa"],
  },
  {
    slug: "andy-amy",
    household: "Andy & Amy",
    type: "weekend",
    stay: "Swinyard Lodge",
    guests: ["Andy", "Amy"],
  },
  {
    slug: "steve",
    household: "Steve",
    type: "weekend",
    stay: "Swinyard Lodge",
    guests: ["Steve"],
  },
  {
    slug: "ben-lindsay",
    household: "Ben & Lindsay",
    type: "day",
    guests: ["Ben", "Lindsay"],
  },
  {
    slug: "nick-kath",
    household: "Nick & Kath",
    type: "day",
    guests: ["Nick", "Kath"],
  },
  {
    slug: "nicki",
    household: "Nicki",
    type: "day",
    guests: ["Nicki"],
  },
  {
    slug: "jo",
    household: "Jo",
    type: "day",
    guests: ["Jo"],
  },
  {
    slug: "amy-henry",
    displayName: "Amy",
    household: "Amy",
    type: "evening",
    guests: ["Amy"],
  },
  {
    slug: "bob-natalie-wells",
    household: "Natalie & Bob",
    type: "evening",
    guests: ["Natalie", "Bob"],
  },
  {
    slug: "elly-henry-thorne",
    household: "Elly & Henry",
    type: "evening",
    guests: ["Elly", "Henry"],
  },
  {
    slug: "jane-knapp",
    household: "Jane",
    type: "evening",
    guests: ["Jane"],
  },
  {
    slug: "leeanne-smith",
    household: "Leeanne",
    type: "evening",
    guests: ["Leeanne"],
  },
  {
    slug: "nita-keeler",
    household: "Nita",
    type: "evening",
    guests: ["Nita"],
  },
  {
    slug: "simon-robertson",
    household: "Simon",
    type: "evening",
    guests: ["Simon"],
  },
  {
    slug: "steph-dutson",
    household: "Steph",
    type: "evening",
    guests: ["Steph"],
  },
  {
    slug: "victoria-power",
    household: "Victoria",
    type: "evening",
    guests: ["Victoria"],
  },
];
